<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGTyAiZn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGTyAiZn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGTyAiZn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGTyAiZn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGTyAiZn\App_KernelDevDebugContainer([
    'container.build_hash' => 'GTyAiZn',
    'container.build_id' => 'db4410de',
    'container.build_time' => 1648584046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGTyAiZn');
